<?php
declare(strict_types=1);

/* Generated by scripts/build_php_cms_installer.py. Do not upload this template. */
const KUAIZ_CMS_INSTALLER_VERSION = '0.9.0';
const KUAIZ_CMS_RELEASE_VERSION = '__KUAIZ_RELEASE_VERSION__';
const KUAIZ_CMS_INSTALL_TOKEN_SHA256 = '__KUAIZ_INSTALL_TOKEN_SHA256__';
const KUAIZ_CMS_PAYLOAD_SHA256 = '__KUAIZ_PAYLOAD_SHA256__';
const KUAIZ_CMS_PAYLOAD_BASE64 = '__KUAIZ_PAYLOAD_JSON_BASE64__';
const KUAIZ_CMS_PAYLOAD_SCHEMA = 'kuaiz-cms-embedded-release/v1';
const KUAIZ_CMS_RELEASE_SIGNATURE_TOKEN = '__KUAIZ_RELEASE_SIGNATURE_TOKEN__';
const KUAIZ_CMS_RELEASE_PUBLIC_KEY_BASE64 = '__KUAIZ_RELEASE_PUBLIC_KEY_BASE64__';
const KUAIZ_CMS_RELEASE_PUBLIC_KEY_FINGERPRINT = '__KUAIZ_RELEASE_PUBLIC_KEY_FINGERPRINT__';
const KUAIZ_CMS_RELEASE_SCHEMA = 'kuaiz-cms-release-signature/v1';
const KUAIZ_CMS_MAX_PAYLOAD_BYTES = 33554432;
const KUAIZ_CMS_FORM_COOKIE = 'kuaiz_cms_install_claim';
const KUAIZ_CMS_FORM_TTL = 1800;
const KUAIZ_CMS_UPGRADE_PAYLOADS = [
    '0.1.6-dev' => '525cf2b2ce770d42ba4c0646bfd8d06a3067edd2b001a9cd4b227b8fb37e4a24',
    '0.1.7-dev' => '2ed1b2a5293ddeb6a13d147010b1759b0ce5c6bae6c15703dda861737a277f1c',
];
const KUAIZ_CMS_MAX_UPGRADE_FILES = 50000;
const KUAIZ_CMS_MAX_UPGRADE_BYTES = 4294967296;

@ini_set('display_errors', '0');
@ini_set('log_errors', '1');

if (!function_exists('array_is_list')) {
    function array_is_list(array $array): bool
    {
        $expectedKey = 0;
        foreach ($array as $key => $_value) {
            if ($key !== $expectedKey) {
                return false;
            }
            $expectedKey++;
        }
        return true;
    }
}

if (!function_exists('str_contains')) {
    function str_contains(string $haystack, string $needle): bool
    {
        return $needle === '' || strpos($haystack, $needle) !== false;
    }
}

if (!function_exists('str_starts_with')) {
    function str_starts_with(string $haystack, string $needle): bool
    {
        return $needle === '' || strncmp($haystack, $needle, strlen($needle)) === 0;
    }
}

header('Cache-Control: private, no-store, max-age=0');
header('X-Robots-Tag: noindex, nofollow, noarchive');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'");

final class KuaizCmsInstallError extends RuntimeException
{
    public string $safeCode;

    public function __construct(string $message, string $safeCode)
    {
        parent::__construct($message);
        $this->safeCode = $safeCode;
    }
}

function kuaiz_cms_install_fail(string $message, string $code): void
{
    throw new KuaizCmsInstallError($message, $code);
}

function kuaiz_cms_install_h(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML5, 'UTF-8');
}

function kuaiz_cms_install_base64url_decode(string $value): string
{
    if ($value === '' || !preg_match('/^[A-Za-z0-9_-]+$/D', $value)) {
        kuaiz_cms_install_fail('安装文件的发行签名格式不正确，请重新下载。', 'release_signature_invalid');
    }
    $decoded = base64_decode(strtr($value, '-_', '+/') . str_repeat('=', (-strlen($value)) & 3), true);
    if (!is_string($decoded)) {
        kuaiz_cms_install_fail('安装文件的发行签名格式不正确，请重新下载。', 'release_signature_invalid');
    }
    return $decoded;
}

function kuaiz_cms_install_canonical_json($value): string
{
    if (is_array($value)) {
        if (array_is_list($value)) {
            foreach ($value as &$item) {
                $item = json_decode(kuaiz_cms_install_canonical_json($item), true, 32, JSON_THROW_ON_ERROR);
            }
            unset($item);
        } else {
            ksort($value, SORT_STRING);
            foreach ($value as &$item) {
                $item = json_decode(kuaiz_cms_install_canonical_json($item), true, 32, JSON_THROW_ON_ERROR);
            }
            unset($item);
        }
    }
    return json_encode(
        $value,
        JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR
    );
}

function kuaiz_cms_install_release_public_key(): string
{
    $pem = base64_decode(KUAIZ_CMS_RELEASE_PUBLIC_KEY_BASE64, true);
    if (!is_string($pem) || strlen($pem) > 16384) {
        kuaiz_cms_install_fail('安装文件的发行公钥不正确，请重新下载。', 'release_public_key_invalid');
    }
    $body = preg_replace(
        '/-----BEGIN PUBLIC KEY-----|-----END PUBLIC KEY-----|\s+/',
        '',
        $pem
    );
    $der = is_string($body) ? base64_decode($body, true) : false;
    $prefix = hex2bin('302a300506032b6570032100');
    if (!is_string($der) || !is_string($prefix) || strlen($der) !== 44
        || !hash_equals($prefix, substr($der, 0, strlen($prefix)))
        || !preg_match('/^[a-f0-9]{64}$/D', KUAIZ_CMS_RELEASE_PUBLIC_KEY_FINGERPRINT)
        || !hash_equals(KUAIZ_CMS_RELEASE_PUBLIC_KEY_FINGERPRINT, hash('sha256', $der))) {
        kuaiz_cms_install_fail('安装文件的发行公钥不正确，请重新下载。', 'release_public_key_invalid');
    }
    return substr($der, strlen($prefix));
}

function kuaiz_cms_install_normalized_source(string $source): string
{
    $placeholders = [
        'RELEASE_VERSION' => 'RELEASE_VERSION',
        'INSTALL_TOKEN_SHA256' => 'INSTALL_TOKEN_SHA256',
        'PAYLOAD_SHA256' => 'PAYLOAD_SHA256',
        'PAYLOAD_BASE64' => 'PAYLOAD_JSON_BASE64',
        'RELEASE_SIGNATURE_TOKEN' => 'RELEASE_SIGNATURE_TOKEN',
        'RELEASE_PUBLIC_KEY_BASE64' => 'RELEASE_PUBLIC_KEY_BASE64',
        'RELEASE_PUBLIC_KEY_FINGERPRINT' => 'RELEASE_PUBLIC_KEY_FINGERPRINT',
    ];
    foreach ($placeholders as $constant => $placeholderName) {
        $pattern = '/^const KUAIZ_CMS_' . preg_quote($constant, '/') . " = '[^'\\r\\n]*';$/m";
        $placeholder = '__' . 'KUAIZ_' . $placeholderName . '__';
        $replacement = "const KUAIZ_CMS_{$constant} = '{$placeholder}';";
        $source = preg_replace($pattern, $replacement, $source, 1, $count);
        if (!is_string($source) || $count !== 1) {
            kuaiz_cms_install_fail('安装器逻辑已被修改，请重新下载。', 'installer_template_modified');
        }
    }
    return $source;
}

function kuaiz_cms_install_verify_release(): array
{
    $parts = explode('.', KUAIZ_CMS_RELEASE_SIGNATURE_TOKEN);
    if (count($parts) !== 3 || $parts[0] !== 'kzc1') {
        kuaiz_cms_install_fail('安装文件的发行签名格式不正确，请重新下载。', 'release_signature_invalid');
    }
    $signedJson = kuaiz_cms_install_base64url_decode($parts[1]);
    $signature = kuaiz_cms_install_base64url_decode($parts[2]);
    if (strlen($signedJson) > 32768 || strlen($signature) !== 64) {
        kuaiz_cms_install_fail('安装文件的发行签名格式不正确，请重新下载。', 'release_signature_invalid');
    }
    try {
        $release = json_decode($signedJson, true, 16, JSON_THROW_ON_ERROR);
    } catch (JsonException $error) {
        throw new KuaizCmsInstallError('安装文件的发行签名无法读取，请重新下载。', 'release_signature_invalid');
    }
    $expectedKeys = [
        'content_bytes', 'database_schema_version', 'file_count', 'issued_at',
        'payload_sha256', 'release_version', 'runtime_profile', 'schema', 'template_sha256',
    ];
    if (!is_array($release) || array_is_list($release) || array_keys($release) !== $expectedKeys
        || ($release['schema'] ?? null) !== KUAIZ_CMS_RELEASE_SCHEMA
        || ($release['release_version'] ?? null) !== KUAIZ_CMS_RELEASE_VERSION
        || ($release['runtime_profile'] ?? null) !== 'community-php-sqlite-v1'
        || !is_int($release['database_schema_version'] ?? null)
        || $release['database_schema_version'] < 1 || $release['database_schema_version'] > 1000000
        || !is_int($release['file_count'] ?? null)
        || $release['file_count'] < 1 || $release['file_count'] > 50000
        || !is_int($release['content_bytes'] ?? null)
        || $release['content_bytes'] < 1 || $release['content_bytes'] > KUAIZ_CMS_MAX_PAYLOAD_BYTES
        || !is_int($release['issued_at'] ?? null) || $release['issued_at'] < 1
        || !is_string($release['payload_sha256'] ?? null)
        || !preg_match('/^[a-f0-9]{64}$/D', $release['payload_sha256'])
        || !hash_equals($release['payload_sha256'], KUAIZ_CMS_PAYLOAD_SHA256)
        || !is_string($release['template_sha256'] ?? null)
        || !preg_match('/^[a-f0-9]{64}$/D', $release['template_sha256'])) {
        kuaiz_cms_install_fail('安装文件的发行摘要不正确，请重新下载。', 'release_envelope_invalid');
    }
    try {
        $canonical = kuaiz_cms_install_canonical_json($release);
    } catch (JsonException $error) {
        throw new KuaizCmsInstallError('安装文件的发行摘要无法读取，请重新下载。', 'release_envelope_invalid');
    }
    $publicKey = kuaiz_cms_install_release_public_key();
    if (!hash_equals($signedJson, $canonical)) {
        kuaiz_cms_install_fail('安装文件的发行签名验证失败，请重新下载。', 'release_signature_invalid');
    }
    if (function_exists('sodium_crypto_sign_verify_detached')
        && !sodium_crypto_sign_verify_detached($signature, $signedJson, $publicKey)) {
        kuaiz_cms_install_fail('安装文件的发行签名验证失败，请重新下载。', 'release_signature_invalid');
    }
    $source = file_get_contents(__FILE__);
    if (!is_string($source)
        || !hash_equals(
            $release['template_sha256'],
            hash('sha256', kuaiz_cms_install_normalized_source($source))
        )) {
        kuaiz_cms_install_fail('安装器逻辑已被修改，请重新下载。', 'installer_template_modified');
    }
    return $release;
}

function kuaiz_cms_install_https(): bool
{
    $direct = strtolower((string)($_SERVER['HTTPS'] ?? ''));
    $forwarded = strtolower(trim(explode(',', (string)($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? ''))[0]));
    return ($direct !== '' && $direct !== 'off') || $forwarded === 'https';
}

function kuaiz_cms_install_document_root(): string
{
    $scriptRoot = realpath(__DIR__);
    $documentRoot = realpath((string)($_SERVER['DOCUMENT_ROOT'] ?? ''));
    if (!is_string($scriptRoot) || !is_string($documentRoot)
        || $scriptRoot !== $documentRoot || is_link(__DIR__) || !is_writable($documentRoot)) {
        kuaiz_cms_install_fail('请把安装文件直接放到空网站的根目录。', 'document_root_invalid');
    }
    return rtrim($documentRoot, DIRECTORY_SEPARATOR);
}

function kuaiz_cms_install_site_base_url(): string
{
    $host = strtolower(trim((string)($_SERVER['HTTP_HOST'] ?? '')));
    if ($host === '' || strlen($host) > 253
        || preg_match('/[\x00-\x20\x7f@\/?#\\\\]/', $host)
        || !preg_match(
            '/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+'
            . '[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?::[1-9][0-9]{0,4})?$/D',
            $host
        )) {
        kuaiz_cms_install_fail('当前访问域名不正确，请通过准备运营的正式域名打开安装文件。', 'site_domain_invalid');
    }
    return (kuaiz_cms_install_https() ? 'https://' : 'http://') . $host;
}

function kuaiz_cms_install_environment(): void
{
    if (PHP_VERSION_ID < 70400) {
        kuaiz_cms_install_fail('当前主机 PHP 版本过低，需要 PHP 7.4 或更高版本。', 'php_version_unsupported');
    }
    $missing = array_values(array_filter(
        ['pdo_sqlite', 'fileinfo', 'gd'],
        static fn(string $extension): bool => !extension_loaded($extension)
    ));
    $gdFunctions = function_exists('getimagesize')
        && function_exists('imagecreatetruecolor')
        && function_exists('imagecopyresampled');
    $imageDecoder = function_exists('imagecreatefromjpeg')
        || function_exists('imagecreatefrompng')
        || function_exists('imagecreatefromwebp');
    $imageEncoder = function_exists('imagewebp')
        || function_exists('imagejpeg')
        || function_exists('imagepng');
    if (!$gdFunctions || !$imageDecoder || !$imageEncoder) {
        $missing[] = 'GD 图片处理';
    }
    if ($missing !== []) {
        kuaiz_cms_install_fail(
            '当前主机缺少：' . implode('、', $missing) . '。请让主机商开启后再安装。',
            'php_extension_missing'
        );
    }
    $software = strtolower((string)($_SERVER['SERVER_SOFTWARE'] ?? ''));
    if (PHP_SAPI !== 'cli' && !str_contains($software, 'apache')
        && !str_contains($software, 'litespeed')) {
        kuaiz_cms_install_fail(
            '当前一键安装首版支持 Apache 或 LiteSpeed PHP 主机；其他服务器需要先配置 URL 改写。',
            'web_server_unsupported'
        );
    }
}

function kuaiz_cms_install_payload(array $release): array
{
    $body = base64_decode(KUAIZ_CMS_PAYLOAD_BASE64, true);
    if (!is_string($body) || strlen($body) > KUAIZ_CMS_MAX_PAYLOAD_BYTES
        || !hash_equals(KUAIZ_CMS_PAYLOAD_SHA256, hash('sha256', $body))) {
        kuaiz_cms_install_fail('安装文件内容不完整，请重新下载。', 'payload_corrupt');
    }
    try {
        $payload = json_decode($body, true, 64, JSON_THROW_ON_ERROR);
    } catch (JsonException $error) {
        throw new KuaizCmsInstallError('安装文件内容无法读取，请重新下载。', 'payload_invalid');
    }
    if (!is_array($payload) || array_is_list($payload)
        || array_keys($payload) !== [
            'database_schema_version', 'files', 'runtime_profile', 'schema', 'totals', 'version'
        ]
        || ($payload['schema'] ?? null) !== KUAIZ_CMS_PAYLOAD_SCHEMA
        || ($payload['version'] ?? null) !== KUAIZ_CMS_RELEASE_VERSION
        || ($payload['runtime_profile'] ?? null) !== 'community-php-sqlite-v1'
        || !is_int($payload['database_schema_version'] ?? null)
        || !is_array($payload['files'] ?? null) || !array_is_list($payload['files'])
        || !is_array($payload['totals'] ?? null) || array_is_list($payload['totals'])) {
        kuaiz_cms_install_fail('安装文件清单不正确，请重新下载。', 'payload_invalid');
    }
    $seen = [];
    $total = 0;
    foreach ($payload['files'] as &$file) {
        if (!is_array($file) || array_is_list($file)
            || array_keys($file) !== ['body_base64', 'byte_size', 'path', 'sha256']) {
            kuaiz_cms_install_fail('安装文件清单不正确，请重新下载。', 'payload_invalid');
        }
        $path = $file['path'] ?? null;
        if (!is_string($path) || isset($seen[$path]) || !kuaiz_cms_install_owned_path($path)
            || !is_int($file['byte_size'] ?? null) || $file['byte_size'] < 1
            || !is_string($file['sha256'] ?? null)
            || !preg_match('/^[a-f0-9]{64}$/D', $file['sha256'])
            || !is_string($file['body_base64'] ?? null)) {
            kuaiz_cms_install_fail('安装文件清单不正确，请重新下载。', 'payload_invalid');
        }
        $decoded = base64_decode($file['body_base64'], true);
        if (!is_string($decoded) || strlen($decoded) !== $file['byte_size']
            || !hash_equals($file['sha256'], hash('sha256', $decoded))) {
            kuaiz_cms_install_fail('安装文件内容校验失败，请重新下载。', 'payload_corrupt');
        }
        $file['decoded'] = $decoded;
        $seen[$path] = true;
        $total += strlen($decoded);
        if ($total > KUAIZ_CMS_MAX_PAYLOAD_BYTES) {
            kuaiz_cms_install_fail('安装文件超过安全大小限制。', 'payload_too_large');
        }
    }
    unset($file);
    ksort($seen);
    $required = [
        'cms-manifest.json', 'src/Compatibility.php', 'src/Database.php', 'src/Auth.php',
        'src/ExtensionManifest.php', 'src/ExtensionRegistry.php',
        'src/ThemeManifest.php', 'src/ThemeRegistry.php', 'src/SiteSettings.php', 'public/index.php',
        'public/.htaccess', 'public/.user.ini',
        'extensions/kuaiz-directory/extension.json', 'themes/kuaiz-studio/theme.json',
        'themes/kuaiz-default/theme.json',
    ];
    foreach ($required as $path) {
        if (!isset($seen[$path])) {
            kuaiz_cms_install_fail('安装文件缺少必要内核，请重新下载。', 'payload_incomplete');
        }
    }
    if (array_keys($payload['totals']) !== ['byte_size', 'file_count']
        || ($payload['totals']['file_count'] ?? null) !== count($payload['files'])
        || ($payload['totals']['byte_size'] ?? null) !== $total
        || $release['file_count'] !== count($payload['files'])
        || $release['content_bytes'] !== $total
        || $release['database_schema_version'] !== $payload['database_schema_version']) {
        kuaiz_cms_install_fail('安装文件汇总校验失败，请重新下载。', 'payload_invalid');
    }
    return $payload;
}

function kuaiz_cms_install_owned_path(string $path): bool
{
    return (bool)preg_match(
        '#^(?:README\.md|cms-manifest\.json|contracts/[a-z0-9.-]+\.json|'
        . 'extensions/[a-z0-9-]+/[a-z0-9.-]+\.json|themes/[a-z0-9-]+/[a-z0-9.-]+\.json|'
        . 'src/[A-Za-z][A-Za-z0-9]+\.php|bin/cms-[a-z-]+\.php|'
        . 'public/(?:index\.php|\.htaccess|\.user\.ini))$#D',
        $path
    );
}

function kuaiz_cms_install_private_root(string $documentRoot): string
{
    $parent = dirname($documentRoot);
    $realParent = realpath($parent);
    $base = is_string($realParent) && !is_link($parent) && is_writable($realParent)
        ? rtrim($realParent, DIRECTORY_SEPARATOR) : $documentRoot;
    $directory = '.kuaiz-cms-' . hash_hmac(
        'sha256',
        $documentRoot,
        KUAIZ_CMS_INSTALL_TOKEN_SHA256
    );
    return $base . '/' . $directory;
}

function kuaiz_cms_install_legacy_private_root(string $documentRoot): string
{
    $parent = dirname($documentRoot);
    $realParent = realpath($parent);
    $base = is_string($realParent) && !is_link($parent) && is_writable($realParent)
        ? rtrim($realParent, DIRECTORY_SEPARATOR) : $documentRoot;
    return $base . '/.kuaiz-cms-' . substr(hash('sha256', $documentRoot), 0, 16);
}

function kuaiz_cms_install_existing_private_root(
    string $documentRoot,
    string $privateRoot
): string {
    if (is_dir($privateRoot)) {
        return $privateRoot;
    }
    $publicLauncher = $documentRoot . '/index.php';
    $launcherBody = is_file($publicLauncher) && !is_link($publicLauncher)
        && filesize($publicLauncher) <= 4096
        ? file_get_contents($publicLauncher) : false;
    if (is_string($launcherBody)) {
        $bases = [dirname($documentRoot), $documentRoot];
        $seen = [];
        $candidateCount = 0;
        foreach ($bases as $base) {
            $realBase = realpath($base);
            if (!is_string($realBase) || isset($seen[$realBase])) {
                continue;
            }
            $seen[$realBase] = true;
            $candidates = glob(rtrim($realBase, DIRECTORY_SEPARATOR) . '/.kuaiz-cms-*', GLOB_ONLYDIR);
            if (!is_array($candidates)) {
                continue;
            }
            $candidateCount += count($candidates);
            if ($candidateCount > 1024) {
                kuaiz_cms_install_fail(
                    '发现过多无法确认的旧安装目录，请联系技术人员处理。',
                    'existing_install_candidates_excessive'
                );
            }
            foreach ($candidates as $candidate) {
                if (is_link($candidate)
                    || !preg_match('/^\.kuaiz-cms-(?:[a-f0-9]{16}|[a-f0-9]{64})$/D', basename($candidate))) {
                    continue;
                }
                if (hash_equals($launcherBody, kuaiz_cms_install_public_launcher($candidate))) {
                    return $candidate;
                }
            }
        }
    }
    $legacy = kuaiz_cms_install_legacy_private_root($documentRoot);
    return is_dir($legacy) ? $legacy : $privateRoot;
}

function kuaiz_cms_install_private_location(
    string $documentRoot,
    string $privateRoot
): string {
    return dirname($privateRoot) === $documentRoot
        ? 'protected-document-root' : 'outside-document-root';
}

function kuaiz_cms_install_private_guard_files(): array
{
    return [
        '.htaccess' => "Options -Indexes\n<IfModule mod_authz_core.c>\n"
            . "    Require all denied\n</IfModule>\n<IfModule !mod_authz_core.c>\n"
            . "    Order allow,deny\n    Deny from all\n</IfModule>\n",
        'index.php' => "<?php\nhttp_response_code(404);\nexit;\n",
    ];
}

function kuaiz_cms_install_write_private_guard(string $stage): void
{
    foreach (kuaiz_cms_install_private_guard_files() as $name => $body) {
        $target = $stage . '/' . $name;
        if (file_put_contents($target, $body, LOCK_EX) !== strlen($body)) {
            kuaiz_cms_install_fail('无法保护 CMS 私有目录。', 'private_guard_write_failed');
        }
        @chmod($target, 0600);
    }
}

function kuaiz_cms_install_existing_target(
    string $documentRoot,
    string $privateRoot,
    array $payload
): array
{
    $receipt = $privateRoot . '/install-receipt.json';
    if (!is_dir($privateRoot)) {
        return ['state' => 'new', 'receipt' => null];
    }
    if (is_link($privateRoot) || !is_file($receipt) || is_link($receipt) || filesize($receipt) > 65536) {
        kuaiz_cms_install_fail('发现无法确认的旧安装目录，请联系技术人员处理。', 'existing_install_unsafe');
    }
    try {
        $value = json_decode((string)file_get_contents($receipt), true, 16, JSON_THROW_ON_ERROR);
    } catch (JsonException $error) {
        throw new KuaizCmsInstallError('旧安装记录已损坏，请联系技术人员处理。', 'existing_install_corrupt');
    }
    if (!is_array($value) || ($value['document_root'] ?? null) !== $documentRoot
        || ($value['release_public_key_fingerprint'] ?? null)
            !== KUAIZ_CMS_RELEASE_PUBLIC_KEY_FINGERPRINT) {
        kuaiz_cms_install_fail('这个目录已安装其他版本，当前安装器不会覆盖。', 'existing_install_mismatch');
    }
    $version = (string)($value['version'] ?? '');
    $payloadSha256 = (string)($value['payload_sha256'] ?? '');
    $state = 'current';
    if ($version === KUAIZ_CMS_RELEASE_VERSION) {
        if (!hash_equals(KUAIZ_CMS_PAYLOAD_SHA256, $payloadSha256)) {
            kuaiz_cms_install_fail('这个目录的安装记录不匹配，当前安装器不会覆盖。', 'existing_install_mismatch');
        }
    } elseif (isset(KUAIZ_CMS_UPGRADE_PAYLOADS[$version])
        && hash_equals(KUAIZ_CMS_UPGRADE_PAYLOADS[$version], $payloadSha256)) {
        $state = 'upgrade';
    } else {
        kuaiz_cms_install_fail('这个目录已安装其他版本，当前安装器不会覆盖。', 'existing_install_mismatch');
    }
    if (kuaiz_cms_install_private_location($documentRoot, $privateRoot)
        === 'protected-document-root') {
        foreach (kuaiz_cms_install_private_guard_files() as $name => $body) {
            $guard = $privateRoot . '/' . $name;
            if (is_link($guard) || !is_file($guard) || file_get_contents($guard) !== $body) {
                kuaiz_cms_install_fail(
                    'CMS 私有目录的访问保护不完整，当前安装器不会继续。',
                    'private_guard_missing'
                );
            }
        }
    }
    if ($state === 'current') {
        foreach ($payload['files'] as $file) {
            $path = $privateRoot . '/' . $file['path'];
            if (is_link($path) || !is_file($path)
                || (int)filesize($path) !== $file['byte_size']
                || !hash_equals($file['sha256'], (string)hash_file('sha256', $path))) {
                kuaiz_cms_install_fail(
                    '旧安装的内核文件不完整，当前安装器不会继续写入公开入口。',
                    'existing_install_corrupt'
                );
            }
        }
    } elseif (is_link($privateRoot . '/var') || !is_dir($privateRoot . '/var')
        || is_link($privateRoot . '/var/cms.sqlite')
        || !is_file($privateRoot . '/var/cms.sqlite')) {
        kuaiz_cms_install_fail('旧安装的数据库不完整，修复已经停止。', 'upgrade_database_missing');
    }
    return ['state' => $state, 'receipt' => $value];
}

function kuaiz_cms_install_check_public_targets(
    string $documentRoot,
    string $privateRoot,
    array $payload,
    ?string $replaceablePrivateRoot = null
): array {
    $launcher = kuaiz_cms_install_public_launcher($privateRoot);
    $files = kuaiz_cms_install_file_map($payload);
    $targets = [
        'index.php' => $launcher,
        '.htaccess' => $files['public/.htaccess'],
        'robots.txt/index.php' => $launcher,
        'sitemap.xml/index.php' => $launcher,
    ];
    foreach ([
        '/admin',
        '/admin/setup',
        '/admin/login',
        '/admin/logout',
        '/admin/content/new',
        '/admin/content/edit',
        '/admin/content/history',
        '/admin/content/save',
        '/admin/content/state',
        '/admin/media',
        '/admin/media/file',
        '/admin/media/upload',
        '/admin/media/update',
        '/admin/media/state',
        '/admin/settings',
        '/admin/themes',
        '/admin/themes/activate',
    ] as $route) {
        $targets[ltrim($route, '/') . '/index.php'] = $launcher;
    }
    clearstatcache(true);
    $adminRoot = $documentRoot . '/admin';
    if (is_link($adminRoot) || (file_exists($adminRoot) && !is_dir($adminRoot))
        || (is_dir($adminRoot) && !is_file($adminRoot . '/index.php'))) {
        kuaiz_cms_install_fail(
            '网站根目录已有 admin 目录，为避免覆盖现有文件，安装已停止。',
            'public_admin_conflict'
        );
    }
    foreach ($targets as $name => $body) {
        $path = $documentRoot . '/' . $name;
        clearstatcache(true, $path);
        $existingBody = is_file($path) && !is_link($path)
            ? file_get_contents($path) : false;
        $replaceableLauncher = $name === 'index.php'
            && is_string($replaceablePrivateRoot)
            && $replaceablePrivateRoot !== $privateRoot
            && $existingBody === kuaiz_cms_install_public_launcher($replaceablePrivateRoot);
        if (is_link($path) || (is_file($path) && $existingBody !== $body
                && !$replaceableLauncher)
            || (file_exists($path) && !is_file($path))) {
            kuaiz_cms_install_fail(
                '网站根目录已有 ' . $name . '，为避免覆盖现有网站，安装已停止。',
                'public_target_conflict'
            );
        }
    }
    return $targets;
}

function kuaiz_cms_install_public_launcher(string $privateRoot): string
{
    return "<?php\ndeclare(strict_types=1);\n/* Kuaiz CMS managed launcher. */\nrequire "
        . var_export($privateRoot . '/public/index.php', true) . ";\n";
}

function kuaiz_cms_install_content_targets(string $privateRoot): array
{
    $database = $privateRoot . '/var/cms.sqlite';
    if (is_link($database) || !is_file($database)) {
        kuaiz_cms_install_fail('网站数据库不完整，无法补上公开页面入口。', 'public_routes_database_missing');
    }
    try {
        $pdo = new PDO('sqlite:' . $database, null, null, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
        $rows = $pdo->query(<<<'SQL'
SELECT ct.route_slug,e.slug
FROM cms_content_types ct
JOIN cms_extensions x ON x.extension_id=ct.extension_id AND x.status='active'
LEFT JOIN cms_entries e ON e.content_type_id=ct.id
ORDER BY ct.route_slug,e.slug
SQL)->fetchAll();
        $pdo = null;
    } catch (Throwable $error) {
        kuaiz_cms_install_fail('无法读取现有公开页面，修复已经停止。', 'public_routes_database_invalid');
    }
    if (!is_array($rows) || count($rows) > KUAIZ_CMS_MAX_UPGRADE_FILES) {
        kuaiz_cms_install_fail('现有公开页面数量异常，修复已经停止。', 'public_routes_count_invalid');
    }
    $launcher = kuaiz_cms_install_public_launcher($privateRoot);
    $targets = [];
    foreach ($rows as $row) {
        $route = is_array($row) ? (string)($row['route_slug'] ?? '') : '';
        $slug = is_array($row) && $row['slug'] !== null ? (string)$row['slug'] : '';
        if (!preg_match('/^[a-z0-9][a-z0-9-]{0,63}$/D', $route)
            || ($slug !== '' && !preg_match('/^[a-z0-9][a-z0-9-]{0,119}$/D', $slug))) {
            kuaiz_cms_install_fail('现有公开页面地址不正确，修复已经停止。', 'public_routes_path_invalid');
        }
        $targets[$route . '/index.php'] = $launcher;
        if ($slug !== '') {
            $targets[$route . '/' . $slug . '/index.php'] = $launcher;
        }
    }
    return $targets;
}

function kuaiz_cms_install_check_additional_public_targets(
    string $documentRoot,
    array $targets
): void {
    foreach ($targets as $name => $body) {
        $path = $documentRoot . '/' . $name;
        clearstatcache(true, $path);
        if (is_link($path) || (is_file($path) && file_get_contents($path) !== $body)
            || (file_exists($path) && !is_file($path))) {
            kuaiz_cms_install_fail(
                '网站根目录已有 ' . $name . '，为避免覆盖现有网站，修复已经停止。',
                'public_route_conflict'
            );
        }
    }
}

function kuaiz_cms_install_file_map(array $payload): array
{
    $result = [];
    foreach ($payload['files'] as $file) {
        $result[$file['path']] = $file['decoded'];
    }
    return $result;
}

function kuaiz_cms_install_directory(string $path, string $root): void
{
    if (is_link($path)
        || (!is_dir($path) && !mkdir($path, 0700, true) && !is_dir($path))
        || is_link($path)) {
        kuaiz_cms_install_fail('无法创建安全的安装目录。', 'directory_create_failed');
    }
    $realRoot = realpath($root);
    $realPath = realpath($path);
    if (!is_string($realRoot) || !is_string($realPath)
        || ($realPath !== $realRoot
            && !str_starts_with($realPath, rtrim($realRoot, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR))) {
        kuaiz_cms_install_fail('安装目录越过安全边界。', 'directory_unsafe');
    }
    @chmod($path, 0700);
}

function kuaiz_cms_install_write_release(string $stage, array $payload): void
{
    foreach ($payload['files'] as $file) {
        $target = $stage . '/' . $file['path'];
        kuaiz_cms_install_directory(dirname($target), $stage);
        if (is_link($target) || file_put_contents($target, $file['decoded'], LOCK_EX) !== $file['byte_size']) {
            kuaiz_cms_install_fail('写入 CMS 内核失败，请检查空间权限。', 'release_write_failed');
        }
        @chmod($target, 0600);
        if (!hash_equals($file['sha256'], (string)hash_file('sha256', $target))) {
            kuaiz_cms_install_fail('写入后的 CMS 内核校验失败。', 'release_verify_failed');
        }
    }
}

function kuaiz_cms_install_write_json(string $path, array $value): void
{
    $body = json_encode(
        $value,
        JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR
    ) . "\n";
    $temporary = $path . '.' . bin2hex(random_bytes(6)) . '.tmp';
    if (file_put_contents($temporary, $body, LOCK_EX) !== strlen($body)) {
        @unlink($temporary);
        kuaiz_cms_install_fail('无法写入安装记录。', 'receipt_write_failed');
    }
    @chmod($temporary, 0600);
    if (!rename($temporary, $path)) {
        @unlink($temporary);
        kuaiz_cms_install_fail('无法提交安装记录。', 'receipt_commit_failed');
    }
}

function kuaiz_cms_install_initialize(
    string $root,
    string $email,
    string $displayName,
    string $password,
    string $siteName,
    string $siteDescription,
    string $siteLanguage,
    string $siteBaseUrl
): void {
    require_once $root . '/src/Database.php';
    require_once $root . '/src/Auth.php';
    require_once $root . '/src/ExtensionManifest.php';
    require_once $root . '/src/ExtensionRegistry.php';
    require_once $root . '/src/ThemeManifest.php';
    require_once $root . '/src/ThemeRegistry.php';
    require_once $root . '/src/SiteSettings.php';
    kuaiz_cms_install_directory($root . '/var', $root);
    $pdo = KuaizCmsDatabase::connect($root . '/var/cms.sqlite');
    $extension = (string)file_get_contents($root . '/extensions/kuaiz-directory/extension.json');
    KuaizCmsExtensionRegistry::installDeclarative(
        $pdo,
        $extension,
        'system:installer',
        '0.1.0'
    );
    $theme = (string)file_get_contents($root . '/themes/kuaiz-studio/theme.json');
    KuaizCmsThemeRegistry::install(
        $pdo,
        $theme,
        $root . '/themes/kuaiz-studio',
        $root . '/var',
        'system:installer',
        '0.1.0',
        false
    );
    $defaultTheme = (string)file_get_contents($root . '/themes/kuaiz-default/theme.json');
    KuaizCmsThemeRegistry::install(
        $pdo,
        $defaultTheme,
        $root . '/themes/kuaiz-default',
        $root . '/var',
        'system:installer',
        '0.1.0',
        true
    );
    $setupToken = KuaizCmsAuth::provisionSetupToken($pdo);
    KuaizCmsAuth::ensureInitialAdmin($pdo, $email, $displayName, $password, $setupToken);
    $languagePrefix = strtolower(explode('-', $siteLanguage, 2)[0]);
    KuaizCmsSiteSettings::save($pdo, [
        'site_name' => $siteName,
        'tagline' => '',
        'description' => $siteDescription,
        'language' => $siteLanguage,
        'direction' => in_array($languagePrefix, ['ar', 'fa', 'he', 'ur'], true) ? 'rtl' : 'ltr',
        'base_url' => $siteBaseUrl,
        'search_indexing' => false,
        'contact_title' => '',
        'contact_summary' => '',
        'cover_media_id' => null,
    ], 'system:installer');
    $pdo = null;
}

function kuaiz_cms_install_copy_existing_data(string $privateRoot, string $stage): void
{
    $source = $privateRoot . '/var';
    $target = $stage . '/var';
    try {
        $pdo = new PDO('sqlite:' . $source . '/cms.sqlite', null, null, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
        if (strtolower((string)$pdo->query('PRAGMA integrity_check')->fetchColumn()) !== 'ok') {
            throw new RuntimeException('database_integrity_failed');
        }
        $pdo->exec('PRAGMA wal_checkpoint(TRUNCATE)');
        $pdo = null;
    } catch (Throwable $error) {
        kuaiz_cms_install_fail('旧安装的数据库检查没有通过，修复已经停止。', 'upgrade_database_invalid');
    }
    kuaiz_cms_install_directory($target, $stage);
    $files = 0;
    $bytes = 0;
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($source, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST
    );
    foreach ($iterator as $item) {
        if ($item->isLink() || (!$item->isDir() && !$item->isFile())) {
            kuaiz_cms_install_fail('旧安装的数据目录包含不安全文件，修复已经停止。', 'upgrade_data_unsafe');
        }
        $relative = substr($item->getPathname(), strlen($source) + 1);
        if (!is_string($relative) || $relative === '' || str_contains($relative, "\0")) {
            kuaiz_cms_install_fail('旧安装的数据路径不安全，修复已经停止。', 'upgrade_data_unsafe');
        }
        $destination = $target . '/' . $relative;
        if ($item->isDir()) {
            kuaiz_cms_install_directory($destination, $stage);
            continue;
        }
        $size = $item->getSize();
        $files++;
        $bytes += $size;
        if ($size < 0 || $files > KUAIZ_CMS_MAX_UPGRADE_FILES
            || $bytes > KUAIZ_CMS_MAX_UPGRADE_BYTES
            || !copy($item->getPathname(), $destination)) {
            kuaiz_cms_install_fail('旧安装的数据无法安全复制，修复已经停止。', 'upgrade_data_copy_failed');
        }
        @chmod($destination, 0600);
    }
    require_once $stage . '/src/Database.php';
    try {
        $pdo = KuaizCmsDatabase::connect($target . '/cms.sqlite');
        if (strtolower((string)$pdo->query('PRAGMA integrity_check')->fetchColumn()) !== 'ok') {
            throw new RuntimeException('database_integrity_failed');
        }
        $pdo = null;
    } catch (Throwable $error) {
        kuaiz_cms_install_fail('复制后的数据库检查没有通过，修复已经停止。', 'upgrade_database_copy_invalid');
    }
}

function kuaiz_cms_install_public_files(
    string $documentRoot,
    array $targets,
    ?string $replaceablePrivateRoot = null
): void
{
    $temporaries = [];
    try {
        foreach ($targets as $name => $body) {
            $target = $documentRoot . '/' . $name;
            if (is_file($target) && file_get_contents($target) === $body) {
                continue;
            }
            kuaiz_cms_install_public_directory(dirname($target), $documentRoot);
            $temporary = $documentRoot . '/.kuaiz-public-' . bin2hex(random_bytes(8));
            if (file_put_contents($temporary, $body, LOCK_EX) !== strlen($body)) {
                kuaiz_cms_install_fail('无法写入网站入口文件。', 'public_write_failed');
            }
            @chmod($temporary, 0644);
            $temporaries[$name] = $temporary;
        }
        foreach ($temporaries as $name => $temporary) {
            $target = $documentRoot . '/' . $name;
            $replaceableLauncher = $name === 'index.php'
                && is_string($replaceablePrivateRoot)
                && is_file($target)
                && !is_link($target)
                && file_get_contents($target)
                    === kuaiz_cms_install_public_launcher($replaceablePrivateRoot);
            if ((file_exists($target) && !$replaceableLauncher)
                || !rename($temporary, $target)) {
                kuaiz_cms_install_fail('无法提交网站入口文件。', 'public_commit_failed');
            }
            unset($temporaries[$name]);
        }
    } finally {
        foreach ($temporaries as $temporary) {
            @unlink($temporary);
        }
    }
}

function kuaiz_cms_install_public_directory(string $path, string $documentRoot): void
{
    if (is_link($path)
        || (!is_dir($path) && !mkdir($path, 0755, true) && !is_dir($path))
        || is_link($path)) {
        kuaiz_cms_install_fail('无法创建网站后台入口目录。', 'public_directory_failed');
    }
    $realDocumentRoot = realpath($documentRoot);
    $realPath = realpath($path);
    if (!is_string($realDocumentRoot) || !is_string($realPath)
        || ($realPath !== $realDocumentRoot
            && !str_starts_with(
                $realPath,
                rtrim($realDocumentRoot, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR
            ))) {
        kuaiz_cms_install_fail('网站后台入口目录越过安全边界。', 'public_directory_unsafe');
    }
    @chmod($path, 0755);
}

function kuaiz_cms_install_remove_deprecated_public_file(
    string $documentRoot,
    array $payload
): void {
    $path = $documentRoot . '/.user.ini';
    $files = kuaiz_cms_install_file_map($payload);
    if (is_file($path) && !is_link($path)
        && file_get_contents($path) === $files['public/.user.ini']) {
        @unlink($path);
    }
}

function kuaiz_cms_install_remove_upgrade_backup(string $path): void
{
    if (!preg_match('#/\.kuaiz-cms-upgrade-backup-[a-f0-9]{16}$#D', $path)
        || is_link($path) || !is_dir($path)) {
        return;
    }
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );
    foreach ($iterator as $item) {
        $item->isDir() && !$item->isLink()
            ? @rmdir($item->getPathname()) : @unlink($item->getPathname());
    }
    @rmdir($path);
}

function kuaiz_cms_install_remove_stage(string $stage): void
{
    if (!preg_match('#/\.kuaiz-cms-stage-[a-f0-9]{16}$#D', $stage) || is_link($stage)) {
        return;
    }
    if (!is_dir($stage)) {
        return;
    }
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($stage, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );
    foreach ($iterator as $item) {
        $item->isDir() && !$item->isLink()
            ? @rmdir($item->getPathname()) : @unlink($item->getPathname());
    }
    @rmdir($stage);
}

function kuaiz_cms_install_create_form_token(): string
{
    $expires = time() + KUAIZ_CMS_FORM_TTL;
    $body = $expires . '.' . bin2hex(random_bytes(32));
    $token = $body . '.' . hash_hmac('sha256', $body, KUAIZ_CMS_INSTALL_TOKEN_SHA256);
    if (!setcookie(KUAIZ_CMS_FORM_COOKIE, $token, [
        'expires' => $expires,
        'path' => '/',
        'secure' => kuaiz_cms_install_https(),
        'httponly' => true,
        'samesite' => 'Strict',
    ])) {
        kuaiz_cms_install_fail('浏览器无法保存本次安装状态，请刷新页面后重试。', 'form_cookie_failed');
    }
    return $token;
}

function kuaiz_cms_install_verify_form_token(): void
{
    $submitted = (string)($_POST['form_token'] ?? '');
    $cookie = (string)($_COOKIE[KUAIZ_CMS_FORM_COOKIE] ?? '');
    if ($submitted === '' || strlen($submitted) > 256
        || $cookie === '' || !hash_equals($cookie, $submitted)) {
        kuaiz_cms_install_fail('安装页面已经失效，请刷新页面后重新填写。', 'form_token_invalid');
    }
    $parts = explode('.', $submitted);
    if (count($parts) !== 3
        || !preg_match('/^[0-9]{10}$/D', $parts[0])
        || !preg_match('/^[a-f0-9]{64}$/D', $parts[1])
        || !preg_match('/^[a-f0-9]{64}$/D', $parts[2])) {
        kuaiz_cms_install_fail('安装页面已经失效，请刷新页面后重新填写。', 'form_token_invalid');
    }
    $expires = (int)$parts[0];
    $now = time();
    $body = $parts[0] . '.' . $parts[1];
    $expected = hash_hmac('sha256', $body, KUAIZ_CMS_INSTALL_TOKEN_SHA256);
    if ($expires < $now || $expires > $now + KUAIZ_CMS_FORM_TTL + 60
        || !hash_equals($expected, $parts[2])) {
        kuaiz_cms_install_fail('安装页面已经失效，请刷新页面后重新填写。', 'form_token_invalid');
    }
}

function kuaiz_cms_install_clear_form_cookie(): void
{
    setcookie(KUAIZ_CMS_FORM_COOKIE, '', [
        'expires' => 1,
        'path' => '/',
        'secure' => kuaiz_cms_install_https(),
        'httponly' => true,
        'samesite' => 'Strict',
    ]);
}

function kuaiz_cms_install_validate_form(): array
{
    kuaiz_cms_install_verify_form_token();
    $email = strtolower(trim((string)($_POST['email'] ?? '')));
    $displayName = trim((string)($_POST['display_name'] ?? ''));
    $password = (string)($_POST['password'] ?? '');
    $confirmation = (string)($_POST['password_confirmation'] ?? '');
    $siteName = trim((string)($_POST['site_name'] ?? ''));
    $siteDescription = trim((string)($_POST['site_description'] ?? ''));
    $siteLanguage = str_replace('_', '-', trim((string)($_POST['site_language'] ?? '')));
    if (filter_var($email, FILTER_VALIDATE_EMAIL) === false || strlen($email) > 128) {
        kuaiz_cms_install_fail('请输入有效的管理员邮箱。', 'admin_email_invalid');
    }
    if ($displayName === '' || strlen($displayName) > 320 || !preg_match('//u', $displayName)
        || preg_match('/[\x00-\x1f\x7f]/', $displayName)) {
        kuaiz_cms_install_fail('请输入有效的管理员称呼。', 'admin_name_invalid');
    }
    if (strlen($password) < 20 || strlen($password) > 1024 || !preg_match('//u', $password)
        || trim($password) === '' || !hash_equals($password, $confirmation)) {
        kuaiz_cms_install_fail('管理员密码至少 20 个字符，并且两次输入必须一致。', 'admin_password_invalid');
    }
    if ($siteName === '' || strlen($siteName) > 480 || !preg_match('//u', $siteName)
        || preg_match('/[\x00-\x1f\x7f]/', $siteName)) {
        kuaiz_cms_install_fail('请填写有效的网站名称。', 'site_name_invalid');
    }
    if ($siteDescription === '' || strlen($siteDescription) > 2000
        || !preg_match('//u', $siteDescription)
        || preg_match('/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/', $siteDescription)) {
        kuaiz_cms_install_fail('请尽量具体地介绍网站业务，最多 500 个字。', 'site_description_invalid');
    }
    if (!preg_match('/^[A-Za-z]{2,3}(?:-(?:[A-Za-z]{2}|[0-9]{3}))?$/D', $siteLanguage)) {
        kuaiz_cms_install_fail('请选择网站唯一使用的语言。', 'site_language_invalid');
    }
    return [$email, $displayName, $password, $siteName, $siteDescription, $siteLanguage];
}

function kuaiz_cms_install_render(
    string $title,
    string $message,
    bool $form,
    int $status,
    string $formToken = '',
    bool $repair = false
): void
{
    http_response_code($status);
    echo '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'
        . kuaiz_cms_install_h($title) . '</title><style>body{margin:0;background:#f4f1e9;color:#17231d;font:16px/1.65 system-ui,sans-serif}.wrap{width:min(680px,calc(100% - 36px));margin:8vh auto}.card{background:#fffdf8;border:1px solid #dcd8ce;border-radius:20px;padding:clamp(24px,5vw,48px);box-shadow:0 18px 48px rgba(15,30,22,.09)}h1{font:700 clamp(32px,6vw,52px)/1.1 Georgia,serif}label{display:block;font-weight:700;margin-top:18px}input,select,textarea{box-sizing:border-box;width:100%;margin-top:7px;padding:12px;border:1px solid #9ba59f;border-radius:10px;background:white;font:inherit}textarea{resize:vertical}button,.button{display:inline-block;margin-top:24px;border:0;border-radius:999px;background:#176146;color:white;padding:12px 22px;font:700 16px system-ui;cursor:pointer;text-decoration:none}.note{color:#617067}.ok{color:#176146;font-weight:700}</style></head><body><main class="wrap"><div class="card"><p class="note">快智 CMS · '
        . kuaiz_cms_install_h(KUAIZ_CMS_RELEASE_VERSION) . '</p><h1>'
        . kuaiz_cms_install_h($title) . '</h1><p>' . kuaiz_cms_install_h($message) . '</p>';
    if ($form) {
        echo '<form method="post" autocomplete="off"><input type="hidden" name="form_token" value="'
            . kuaiz_cms_install_h($formToken) . '">';
        if ($repair) {
            echo '<button type="submit">修复并打开网站后台</button></form><p class="note">公开页面和后台入口会一起修复；现有管理员、网站设置、内容和图片都会保留。</p>';
        } else {
            echo '<label>网站名称<input name="site_name" required maxlength="120" autocomplete="organization"></label><label>网站唯一语言<select name="site_language" required><option value="zh-CN">简体中文</option><option value="zh-TW">繁體中文</option><option value="en">English</option><option value="es">Español</option><option value="pt-BR">Português (Brasil)</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="ja">日本語</option><option value="ko">한국어</option><option value="ar">العربية</option><option value="hi">हिन्दी</option><option value="id">Bahasa Indonesia</option></select></label><label>详细介绍你的业务<textarea name="site_description" required maxlength="500" rows="5" placeholder="服务对象是谁、提供什么产品或服务、所在地区、主要优势和客户最关心的问题。信息越具体，后续网站方案和 FAQ 越准确。"></textarea></label><label>管理员邮箱<input type="email" name="email" required maxlength="128" autocomplete="email"></label><label>怎么称呼你<input name="display_name" required maxlength="100" autocomplete="name"></label><label>管理员密码<input type="password" name="password" required minlength="20" maxlength="1024" autocomplete="new-password"></label><label>再输入一次密码<input type="password" name="password_confirmation" required minlength="20" maxlength="1024" autocomplete="new-password"></label><button type="submit">安装并进入网站后台</button></form><p class="note">安装后默认禁止搜索引擎收录，内容准备好后可在后台开启。已有网站文件不会被覆盖。</p>';
        }
    } elseif ($status === 200) {
        echo '<p><a class="button" href="/admin/">打开网站后台</a></p>';
    }
    echo '</div></main></body></html>';
    exit;
}

$stage = null;
$upgradeBackup = null;
$legacyRootToRemove = null;
try {
    $release = kuaiz_cms_install_verify_release();
    $method = strtoupper((string)($_SERVER['REQUEST_METHOD'] ?? 'GET'));
    if ($method === 'GET') {
        kuaiz_cms_install_environment();
        $payload = kuaiz_cms_install_payload($release);
        $documentRoot = kuaiz_cms_install_document_root();
        kuaiz_cms_install_site_base_url();
        $privateRoot = kuaiz_cms_install_private_root($documentRoot);
        $legacyRoot = kuaiz_cms_install_legacy_private_root($documentRoot);
        $existingRoot = kuaiz_cms_install_existing_private_root(
            $documentRoot,
            $privateRoot
        );
        if (is_dir($existingRoot) && $existingRoot !== $legacyRoot) {
            $privateRoot = $existingRoot;
        }
        kuaiz_cms_install_check_public_targets(
            $documentRoot,
            $privateRoot,
            $payload,
            is_dir($legacyRoot) ? $legacyRoot : null
        );
        $existing = kuaiz_cms_install_existing_target(
            $documentRoot,
            $existingRoot,
            $payload
        );
        $formToken = kuaiz_cms_install_create_form_token();
        $repair = $existing['state'] !== 'new';
        $environmentMessage = $repair
            ? '已经找到现有网站。点击一次即可修复公开页面和后台入口，管理员、设置、内容和图片都会保留。'
            : '当前 PHP ' . PHP_VERSION
                . ' 和安装文件已经检查通过。填写下面的信息，点击一次就能完成安装。';
        if (PHP_VERSION_ID < 80200) {
            $environmentMessage .= '这个 PHP 版本可以兼容运行，正式运营时建议联系主机商升级到 PHP 8.2 或更高版本。';
        }
        if (!kuaiz_cms_install_https()) {
            $environmentMessage .= '当前域名没有 HTTPS，仍然可以安装；但密码在传输中没有加密，请避免使用公共 Wi-Fi，并在条件允许时尽快开启 HTTPS。';
        }
        if (kuaiz_cms_install_private_location($documentRoot, $privateRoot)
            === 'protected-document-root') {
            $environmentMessage .= '这台主机不能写入网站根目录的上一级，系统会自动使用根目录内的受保护私有位置。';
        }
        kuaiz_cms_install_render(
            '开始安装快智 CMS',
            $environmentMessage,
            true,
            200,
            $formToken,
            $repair
        );
    }
    if ($method !== 'POST') {
        header('Allow: GET, POST');
        kuaiz_cms_install_render('无法安装', '只接受浏览器安装表单。', false, 405);
    }
    if ((int)($_SERVER['CONTENT_LENGTH'] ?? 0) > 16384) {
        kuaiz_cms_install_fail('提交内容过大。', 'request_too_large');
    }
    kuaiz_cms_install_environment();
    $payload = kuaiz_cms_install_payload($release);
    $documentRoot = kuaiz_cms_install_document_root();
    $siteBaseUrl = kuaiz_cms_install_site_base_url();
    $privateRoot = kuaiz_cms_install_private_root($documentRoot);
    $legacyRoot = kuaiz_cms_install_legacy_private_root($documentRoot);
    $existingRoot = kuaiz_cms_install_existing_private_root(
        $documentRoot,
        $privateRoot
    );
    if (is_dir($existingRoot) && $existingRoot !== $legacyRoot) {
        $privateRoot = $existingRoot;
    }
    $targets = kuaiz_cms_install_check_public_targets(
        $documentRoot,
        $privateRoot,
        $payload,
        is_dir($legacyRoot) ? $legacyRoot : null
    );
    $existing = kuaiz_cms_install_existing_target(
        $documentRoot,
        $existingRoot,
        $payload
    );
    if (is_dir($legacyRoot) && $legacyRoot !== $privateRoot) {
        $legacyExisting = $legacyRoot === $existingRoot
            ? $existing
            : kuaiz_cms_install_existing_target($documentRoot, $legacyRoot, $payload);
        if ($legacyExisting['state'] === 'upgrade') {
            $legacyRootToRemove = $legacyRoot;
        }
    }
    if ($existing['state'] === 'new') {
        [$email, $displayName, $password, $siteName, $siteDescription, $siteLanguage]
            = kuaiz_cms_install_validate_form();
    } else {
        kuaiz_cms_install_verify_form_token();
        $email = $displayName = $password = $siteName = $siteDescription = '';
        $siteLanguage = (string)($existing['receipt']['site_language'] ?? '');
        if (!preg_match('/^[A-Za-z]{2,3}(?:-(?:[A-Za-z]{2}|[0-9]{3}))?$/D', $siteLanguage)) {
            kuaiz_cms_install_fail('旧安装的网站语言记录不完整，修复已经停止。', 'upgrade_receipt_invalid');
        }
    }
    if ($existing['state'] !== 'current') {
        $stage = dirname($privateRoot) . '/.kuaiz-cms-stage-' . bin2hex(random_bytes(8));
        if (file_exists($stage) || is_link($stage) || !mkdir($stage, 0700, false)) {
            kuaiz_cms_install_fail('无法创建临时安装目录。', 'stage_create_failed');
        }
        kuaiz_cms_install_write_private_guard($stage);
        kuaiz_cms_install_write_release($stage, $payload);
        if ($existing['state'] === 'upgrade') {
            kuaiz_cms_install_copy_existing_data($existingRoot, $stage);
        } else {
            kuaiz_cms_install_initialize(
                $stage,
                $email,
                $displayName,
                $password,
                $siteName,
                $siteDescription,
                $siteLanguage,
                $siteBaseUrl
            );
        }
        kuaiz_cms_install_write_json($stage . '/install-receipt.json', [
            'schema' => 'kuaiz-cms-install-receipt/v1',
            'version' => KUAIZ_CMS_RELEASE_VERSION,
            'payload_sha256' => KUAIZ_CMS_PAYLOAD_SHA256,
            'release_issued_at' => $release['issued_at'],
            'release_public_key_fingerprint' => KUAIZ_CMS_RELEASE_PUBLIC_KEY_FINGERPRINT,
            'document_root' => $documentRoot,
            'private_location' => kuaiz_cms_install_private_location(
                $documentRoot,
                $privateRoot
            ),
            'site_base_url' => $siteBaseUrl,
            'site_language' => $siteLanguage,
            'installed_at' => $existing['state'] === 'upgrade'
                ? (int)($existing['receipt']['installed_at'] ?? time()) : time(),
            'upgraded_at' => $existing['state'] === 'upgrade' ? time() : null,
        ]);
        if ($existing['state'] === 'upgrade') {
            if ($existingRoot !== $privateRoot) {
                if (file_exists($privateRoot) || !rename($stage, $privateRoot)) {
                    kuaiz_cms_install_fail(
                        '无法提交修复后的程序，原网站没有改动。',
                        'upgrade_commit_failed'
                    );
                }
            } else {
                $upgradeBackup = dirname($privateRoot) . '/.kuaiz-cms-upgrade-backup-'
                    . bin2hex(random_bytes(8));
                if (file_exists($upgradeBackup) || !rename($privateRoot, $upgradeBackup)) {
                    kuaiz_cms_install_fail(
                        '无法安全备份现有网站，修复已经停止。',
                        'upgrade_backup_failed'
                    );
                }
                if (!rename($stage, $privateRoot)) {
                    @rename($upgradeBackup, $privateRoot);
                    $upgradeBackup = null;
                    kuaiz_cms_install_fail(
                        '无法提交修复后的程序，原网站已经恢复。',
                        'upgrade_commit_failed'
                    );
                }
            }
        } elseif (file_exists($privateRoot) || !rename($stage, $privateRoot)) {
            kuaiz_cms_install_fail('无法提交 CMS 私有内核。', 'private_commit_failed');
        }
        $stage = null;
    }
    $contentTargets = kuaiz_cms_install_content_targets($privateRoot);
    kuaiz_cms_install_check_additional_public_targets($documentRoot, $contentTargets);
    $targets = array_merge($targets, $contentTargets);
    kuaiz_cms_install_public_files(
        $documentRoot,
        $targets,
        is_dir($legacyRoot) ? $legacyRoot : null
    );
    kuaiz_cms_install_remove_deprecated_public_file($documentRoot, $payload);
    if (is_string($upgradeBackup)) {
        kuaiz_cms_install_remove_upgrade_backup($upgradeBackup);
        $upgradeBackup = null;
    }
    if (is_string($legacyRootToRemove) && is_dir($legacyRootToRemove)) {
        $legacyBackup = dirname($legacyRootToRemove) . '/.kuaiz-cms-upgrade-backup-'
            . bin2hex(random_bytes(8));
        if (file_exists($legacyBackup) || !rename($legacyRootToRemove, $legacyBackup)) {
            kuaiz_cms_install_fail(
                '新后台已经可以使用，但旧程序目录没有清理完成，请重新打开安装文件再试一次。',
                'legacy_cleanup_failed'
            );
        }
        kuaiz_cms_install_remove_upgrade_backup($legacyBackup);
        $legacyRootToRemove = null;
    }
    $deleted = @unlink(__FILE__);
    kuaiz_cms_install_clear_form_cookie();
    $message = $deleted
        ? '处理完成。安装文件已自动删除，现在可以打开 /admin/ 登录。'
        : '处理完成。请手动删除这个安装文件，然后打开 /admin/ 登录。';
    kuaiz_cms_install_render(
        $existing['state'] === 'new' ? '网站已经装好' : '网站入口已经修复',
        $message,
        false,
        200
    );
} catch (KuaizCmsInstallError $error) {
    error_log('Kuaiz CMS install failed [' . $error->safeCode . ']: ' . $error->getMessage());
    if (is_string($stage) && file_exists($stage)) {
        kuaiz_cms_install_remove_stage($stage);
        $stage = null;
    }
    kuaiz_cms_install_render('这次没有安装', $error->getMessage(), false, 400);
} catch (Throwable $error) {
    $errorReference = strtoupper(substr(hash(
        'sha256',
        get_class($error) . '|' . $error->getMessage() . '|' . microtime(true)
    ), 0, 10));
    error_log('Kuaiz CMS install failed [' . $errorReference . ']: ' . $error->getMessage());
    if (is_string($stage) && file_exists($stage)) {
        kuaiz_cms_install_remove_stage($stage);
        $stage = null;
    }
    kuaiz_cms_install_render(
        '这次没有安装',
        '主机在安装过程中返回异常。现有网站文件不会被主动覆盖。请把错误编号 '
            . $errorReference . ' 发给技术人员。',
        false,
        500
    );
} finally {
    if (is_string($stage) && file_exists($stage)) {
        kuaiz_cms_install_remove_stage($stage);
    }
}
